# Generated by Django 5.2 on 2025-05-06 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('E', '전자기기'), ('W', '지갑'), ('B', '가방'), ('C', '카드'), ('L', '의류'), ('K', '열쇠'), ('D', '서류'), ('X', '기타')], default='X', max_length=2)),
                ('status', models.CharField(choices=[('LOST', '분실'), ('FOUND', '습득'), ('RETURNED', '반환')], default='LOST', max_length=8)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
