# Generated by Django 5.2 on 2025-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_images/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('E', '전자기기'), ('W', '지갑'), ('B', '가방'), ('C', '카드'), ('L', '의류'), ('K', '열쇠'), ('D', '서류'), ('X', '기타')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
