# Generated by Django 5.2 on 2025-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_user_id_lostitem_user_lostitem_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
